pipeline/config-diff.sh
When sourcing kayobe-env from the generate_config function, it would get
the function parameters as arguments, which would make it fail. Remove
the function parameters using `shift $#` after saving them to variables.
=> Fix sourcing of kayobe-env

docker/kayobe/Dockerfile
The centos 8 package mirrors have been retired.
=> Switch to using centos 8 stream for the base OS

docker/kayobe/Dockerfile
The issue we are seeing is:
```
[root@ac99140be16b /]# /usr/bin/rsync -F --compress --recursive --rsh=/usr/bin/ssh stack@192.168.45.182:/tmp/a /stack/tempest-artifacts
rsync: on remote machine: --sparse-block=1024: unknown option
```
It has been reported here: https://bugzilla.redhat.com/show_bug.cgi?id=2043753 and a fix is being worked on. Obviously this change has a limited lifetime, but the alternative of using `--sparse-block=0`, has issues too. For example, it won't work on rsync versions that lack this patch. The plan is to revert this change once a new version of rsync, that isn't affected by this bug, has been released.
=> Workaround broken rsync package

.github/workflows/ci.yml
DEV-1359
Syncing the versions of community actions used to the latest major version.
This should avoid deprecation warnings seen in GitHub Actions.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> CI: Update versions used of community GitHub Actions

docker/kayobe/Dockerfile
This change adds an argument to change the base image when building a kayobe container image, with support for rocky linux 9. This is required for the Zed release of Openstack because there is no support for CentOS 8.
Ideally it'd be a bit more flexible with the exact image used but this is already a bit of a yak-shave away from what I should be doing at the moment anyway.
=> Allow rockylinux:9 base image

ansible/roles/config-diff-vars/filter_plugins/utils.py
Jinja2 3.1.0 has dropped `contextfilter` in favour of `pass_filter`
Fortunately `pass_filter` can be used as drop-in replacement `contextfilter` and has been used in projects such as [tenks](https://opendev.org/openstack/tenks/src/branch/master/ansible/filter_plugins/tenks.py#L19) to resolve the same issue.
=> fix: jinja2 contextfilter -> pass_context

functions
GitHub pull request creation can fail for various reasons [1], and
should return a 4XX code if it does.
Previously the response code was ignored (the default behaviour of
curl), so PR creation could silently fail. This change adds the curl
--fail argument, as is used for Gitlab.
[1] https://docs.github.com/en/free-pro-team@latest/rest/pulls/pulls?apiVersion=2022-11-28#create-a-pull-request--status-codes
=> Fail if GitHub PR creation fails

functions
Adds a flag to allow the current copy of kayobe-config to be used, rather than copying in a clean version.
This is useful if you want to use previously-generated Kolla config under kayobe-config/etc/kolla
=> Optionally allow SKC checkout to persist

docker/kayobe/Dockerfile
During Ansible playbook runs `ansible_facts` doesn't get populated unless this package is installed.
=> feat: add `iproute` for Rocky Linux 9

docker/kayobe/Dockerfile
Added a slash to the end of a directory destination as per the user documents.
https://docs.docker.com/engine/reference/builder/#copy
=> Added a slash to the end of a copy command destination.

README.md, functions
The variable `KAYOBE_AUTOMATION_SSH_PRIVATE_KEY_NAME` allows for alternative key names to be used instead of the hardcoded `id_rsa.`
Note: It defaults to `id_rsa` to prevent any breaking changes.
=> feat: Add `KAYOBE_AUTOMATION_SSH_PRIVATE_KEY_NAME`

functions
Attempting to `chmod` the key failed due to the `~` contained within the double quotes.
=> fix: remove `~` from double quotes

scripts/config-diff.sh
Remove the need to manage `KAYOBE_CONFIG_VAULTED_FILES_PATHS_EXTRA` which can be annoying having to update this as new vaulted files get added.
=> feat: find vaulted files automatically for `config-diff`

ansible/kayobe-automation-run-tempest.yml
The tempest_cacert variable may specify the CA certificate path.
Depends on https://github.com/stackhpc/docker-rally/pull/16
=> Add support for specifying a CA certificate for Rally/Tempest

docker/kayobe/Dockerfile
Now CentOS8 stream has been EoL'd, the repos aren't available any more.   This updates the Docker container to use the vault repos instead
=> enable CentOS 8 stream vault repos

utils/kayobe-automation-redact
Some secrets when redacted are rejected due to invalid characters. One example of this would `prometheus_bcrypt_salt` which is rejected due to the use of underscores. Therefore the solution is to add support for exceptions to the standard annotation format.
See: https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/encrypt.py#L118C46-L118C46
https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/prometheus/templates/prometheus-web.yml.j2#L3
=> feat: add support for exceptions to annotations

docker/kayobe/Dockerfile
The default build options can no longer generate a working container.
Centos 8 Stream EOL was 31.05.24 - per https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/
The centos:stream8 image has the default URL for repos, which are deprecated.
Archived packages are available in the vault repository. There will be no further package builds.
Rather than update the repos to use an archival vault, let's switch to a base that is consistent but still actively maintained.
This gives additional time until for migration until Rocky Linux 9 as default https://github.com/stackhpc/kayobe-automation/pull/50. 
Note that the rockylinux:8 image does not include xargs by default. This is used in the build process. xargs is provided by the findutils package which has …
=> Use Rocky Linux 8 container base image by default 

scripts/config-diff.sh
Add support for generating configurations in parallel during `config-diff`.
The source config (base+PR) `stdout` will be displayed during the process however the target config (base only) will be sent to `/dev/null`.
`ANSIBLE_LOG_PATH` for both configurations has been set for extraction in case of error during creation. This would require change to workflows for uploading the file as an artifact.
Process appears to function as expected no noise related to fluentd templates. Maybe I am missing something in my config to encounter this issue.
```
The diff was non-empty. Please check the diff output.
diff -Nur /tmp/tmp.yX2Gm5qjNI-configgen-target/controller-01/horizon/custom_local_settings /tmp/tmp.yJwbxPkga4-configgen-source/controller-01/horizon/custom_local_settings
--- …
```
=> feat: perform config generation in parallel

docker/kayobe/Dockerfile
Allows us to use these roles in hooks, e.g. pre host configures
Fixing an issue where a pre-host-configure hook was unable to use the grubcmdline role:
ERROR! the role 'stackhpc.linux.grubcmdline' was not found in /stack/kayobe-automation-env/src/kayobe-config/etc/kayobe/ansible/roles:/stack/.ansible/kayobe-automation-roles:/stack/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/stack/kayobe-automation-env/src/kayobe-config/etc/kayobe/ansible
=> Include internal Kayobe roles/collections in PATHs

scripts/config-diff.sh
Due to the use of `| .. >` it is possible for the command on the right to run before the left. This can cause situations whereby `md5sum` attempts to hash what is an empty file as `>` operator will clear the file before writing.
=> fix!: store vaulted file hash in temporary variable

docker/kayobe/Dockerfile
Noticed within some deployments and [CI](https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/11945760874/) testing it appears that the building the image fails due to missing selinux python bindings.
```
71.87 Exception: Failed to detect selinux python bindings at ['/usr/local/lib64/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/usr/lib64/python3.9/site-packages', '/usr/lib/python3.9/site-packages']
71.90 Failed to install Ansible roles from /stack/kayobe-automation-env/venvs/kayobe/share/kayobe/requirements.yml via Ansible Galaxy: returncode 1
71.92 Control host bootstrap failed - likely Ansible Galaxy flakiness. Retrying
71.92 [Call Trace]
```
This can be resolved by installing `python3-libselinux`
=> fix: install `python3-libselinux` to avoid exception

ansible/kayobe-automation-run-tempest.yml
Add support for HTTP, HTTPS, and NO_PROXY environment variables in the Tempest container. This allows the container to work properly in environments that require proxy configuration for network access.
The following proxy-related environment variables are now supported:
- TEMPEST_HTTP_PROXY
- TEMPEST_HTTPS_PROXY
- TEMPEST_NO_PROXY Variables are configurable in kayobe-config .automtion.conf/config.sh
Variables are configurable in kayobe-config .automtion.conf/config.sh
=> (feat) Add proxy support to Tempest container

.github/workflows/ci.yml
The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025.
Ubuntu-latest (Noble) appears to work here
=> Stop using Ubuntu Focal runners
